epochs =                5
instance_number =       1556
instance_words_length = 280
instance_words_dim =    512
target_class_number =   144
onnx_dynamo_inference_input =      "input"
onnx_dynamo_inference_output =     "output"
onnx_torchscript_inference_input = "residual_x"
onnx_torchscript_inference_output ="classifer_1"
ondevice_inference_input =         "input"
ondevice_inference_output =        "output"
environment_name =                 "onnxinference"
data_name =                        "Data_ondevice_train"
label_name =                       "Label_ondevice_train"
data_path =                        "../../Desktop/data_binary_shuffle/"
label_path =                       "../../Desktop/data_binary_shuffle/"
onnx_dynamo_inference_path =       "../../Desktop/onnx/train.onnx"
onnx_torchscript_inference_path =  "../../Desktop/onnx/infer.onnx"
ondevice_inference_path =          "../../Desktop/artifacts/inference.onnx"
